version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: tnsquery:${TNSQUERY_VERSION:-latest}
    restart: always
    environment:
      TNSQUERY_RELOAD: "True"
      TNSQUERY_HOST: localhost
      TNSQUERY_DB_HOST: openmediavault.local
      TNSQUERY_DB_PORT: 5432
      TNSQUERY_DB_USER: tnsquery
      TNSQUERY_DB_PASS: tnsquery
      TNSQUERY_DB_BASE: tnsquery
    ports:
      # Exposes application port.
    - "8001:8001"
    volumes:
      # Adds current directory as volume.
    - .:/app/src
    env_file:
    - .env
